pdns:
  image: interlegis/powerdns:4.0.1-1
  links:
    - "mysql:mysql"
  ports:
    - "53:53"
    - "53:53/udp"
    - "8088:8081"
  environment:
    - PDNSCONF_API_KEY=passwd
    - PDNSCONF_MASTER=yes
    - PDNSCONF_DEFAULT_SOA_NAME=dnsserver.domain.com
    - PDNSCONF_DNSUPDATE=yes
    - SECALLZONES_CRONJOB=yes

mysql:
  image: bitnami/mariadb:latest
  environment:
    - MARIADB_ROOT_PASSWORD=mysqlrootpw
    - MARIADB_REPLICATION_MODE=master
    - MARIADB_REPLICATION_USER=repl_user
    - MARIADB_REPLICATION_PASSWORD=repl_password
    - MARIADB_DATABASE=pdns
    - MARIADB_USER=pdns
    - MARIADB_PASSWORD=pdnspw
nsedit:
  image: bgpat/docker-nsedit
  links:
    - "pdns:pdns"
  ports:
    - "8080:8080"
  environment:
    - API_PASS=passwd
    - API_HOST=pdns
    - API_PORT=8081
